#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long 'HelpMessage';
use List::MoreUtils qw(firstidx);

my $usage=<<_EOH_;;
------------------------------------------------------------------------------------------
This script is used to output the PCA plot from a reads number matrix
print command to a Rscript and then run it to output the plot

Usage: 
hclust --matrix total_Common.gene.matrix --samples coldata_common.txt --title Common --column Site_2

Example:
1. --matrix: Blenny_read_nb.xls

	B61	B62	B63	B64	B65	B66	B67	B68	B69	B71	B72	B73	B74	B75	B76	B77	B78	B79
OG0038649	430	218	222	486	402	612	266	159	278	334	365	190	614	464	346	543	477	490
OG0039547	0	1	0	0	0	0	0	0	0	0	0	3	0	0	0	0	0	0

2. --samples: coldata_Blenny.txt

	Site_1	Site_2	Species
B61	Vn	Vent	Blenny
B62	Vn	Vent	Blenny

																			Kang 2021-8-20
------------------------------------------------------------------------------------------
_EOH_
;


GetOptions(
	'matrix:s', \my $matrix,	# the overall reads number matrix
	'samples:s', \ my $sample_file,	# the sample information
	'column:s', \my $col, # the column selected from the sample information
	'title:s', \my $title, # the title
	'help', \ my $help
	);

if ($help || (! $matrix) && (! $sample_file) || (!$col) || (!$title)) {
	die $usage; # all of these options are mandatory requirements
}

main: {
	&creat_R_script();
	exit(0);
}

###################################################################################
sub creat_R_script {
	my $output=$title.".pdf";
	open HCLUST, ">hclust.R" or die "can not creat hclust.R\n";
	print HCLUST "library(ape)\n";
	print HCLUST "library(dendextend)\n";
	print HCLUST "data <- read.table(file=\"$matrix\",header=TRUE,row.names = 1)\n";
	print HCLUST "coldata <- read.table(file=\"$sample_file\")\n";
	print HCLUST "c <- cor(data, method=\"pearson\")\n";
	print HCLUST "d <- as.dist(1-c)\n";
	print HCLUST "d <- as.dist(1-c)\n";
	print HCLUST "hc <- hclust(d, method = \"complete\", members=NULL)\n";
	print HCLUST "dend <- as.dendrogram(hc)\n";
	my ($labels_colors, $total_branch_color, $legend, $fill, $total_ind)=&select_colour();
	$title=~s/_/ /g;
#	print HCLUST "groupCodes <- c($total_ind)\n";
	print HCLUST "colorCodes <- c($labels_colors)\n";
	print HCLUST "labels_colors(dend) <- colorCodes[labels(dend)]\n";
#	print HCLUST "labels_colors(dend) <- colorCodes[groupCodes][order.dendrogram(dend)]\n";
#	print HCLUST "labels_colors(dend) <- c($labels_colors)\n";
	print HCLUST "pdf(file = \"$output\", width = 11.69, height = 8.27)\n";
	print HCLUST "dend \%\>\% ";
	print HCLUST "$total_branch_color\n";
	print HCLUST "legend(\"topright\", legend = c($legend), fill = c($fill))\n";
	print HCLUST "dev.off()";
	close HCLUST;
	`R --no-save --no-restore --no-site-file --no-init-file -q < hclust.R 1>&2`;
	`rm hclust.R`;
}

sub select_colour {
	my @colors=qw(DC0000FF F39B7F99 7E6148FF 00A087FF 4DBBD5FF 8491B4FF); # the maximum number of colour is 6
	open SAMP, "$sample_file" or die "can not open $sample_file\n";
	my $idx;
	my @level;
	my  %hash;
	while (<SAMP>) {
		chomp;
		my @a=split;
		if (/^\s+/) {
			$idx = firstidx { $_ eq $col } @a;
		} else {
			$hash{$a[$idx+1]} .= $a[0]."_";
		}
	}
	my $level_nb=keys %hash;
	my $i=-1;
	my ($labels_colors, $total_branch_color, $legend, $fill, $total_ind);
	foreach my $level (keys %hash) {
		$i++;
		$legend.="\"$level\"".", ";
		my $branch_col;
		my $colour=$colors[$i];
		$fill.="\"#$colour\"".", ";
		my @ind=split /\_/, $hash{$level};
		my $ind_level;
		foreach my $ind (@ind) {
			$labels_colors.=$ind."="."\"#$colour\"".", ";
			$ind_level.="\"$ind\"".", ";
			$total_ind.="\"$ind\"".", ";
		}
		$ind_level=~s/\,\s+$//;
		$branch_col="set(\"by_labels_branches_col\", value = c($ind_level),TF_values = c(\"#$colour\",Inf))";
		$total_branch_color.=$branch_col." \%\>\%\n  ";
	}
	$labels_colors=~s/\,\s+$//;
	$fill=~s/\,\s+$//;
	$legend=~s/\,\s+$//;
	$total_ind=~s/\,\s+$//;
	$total_branch_color.="plot(main = \"$title hclust\")";
	return($labels_colors, $total_branch_color, $legend, $fill, $total_ind);
}
